// Colored background placeholder images via placehold.co
const color = (hex: string, w = 600, h = 800) => `https://placehold.co/${w}x${h}/${hex}/white?text=+`;

export const sellers = [
  { name: 'Yarn \u0026 Bloom Studio', slug: 'yarn-and-bloom', email: 'yarn@demo.com', description: 'Handcrafted crochet pieces made with love and premium yarn.', location: 'Quezon City, Metro Manila', logo: 'https://images.unsplash.com/photo-1614786269829-d24616faf56d?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=1200&h=400&fit=crop' },
  { name: 'Petals \u0026 Thread', slug: 'petals-and-thread', email: 'petals@demo.com', description: 'Beautiful crochet flower bouquets for every occasion.', location: 'Makati City', logo: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=1200&h=400&fit=crop' },
  { name: 'Fuzzy Wonders', slug: 'fuzzy-wonders', email: 'fuzzy@demo.com', description: 'Adorable fuzzy wire art and bouquets handmade with care.', location: 'Cebu City', logo: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&h=400&fit=crop' },
  { name: 'Stitch \u0026 Soul', slug: 'stitch-and-soul', email: 'stitch@demo.com', description: 'Crocheted accessories and wearables for the modern artisan lover.', location: 'Davao City', logo: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&h=400&fit=crop' },
  { name: 'Tiny Hooks PH', slug: 'tiny-hooks-ph', email: 'tiny@demo.com', description: 'Mini stuffed toys and keychains that fit in your palm.', location: 'Pasig City', logo: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1558901357-ca41e027244b?w=1200&h=400&fit=crop' },
  { name: 'Knot So Basic', slug: 'knot-so-basic', email: 'knot@demo.com', description: 'Statement crochet tops and fashion pieces.', location: 'Taguig City', logo: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=1200&h=400&fit=crop' },
  { name: 'Loop \u0026 Lace', slug: 'loop-and-lace', email: 'loop@demo.com', description: 'Elegant hair ties and accessories handcrafted from yarn.', location: 'Manila', logo: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=1200&h=400&fit=crop' },
  { name: 'The Cozy Hook', slug: 'the-cozy-hook', email: 'cozy@demo.com', description: 'Warm, cozy crochet items perfect for gifting.', location: 'Baguio City', logo: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=400&fit=crop' },
  { name: 'Bloom Craft Co.', slug: 'bloom-craft-co', email: 'bloom@demo.com', description: 'Artisan flower arrangements made from wire and yarn.', location: 'Iloilo City', logo: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=1200&h=400&fit=crop' },
  { name: 'Handmade Haven', slug: 'handmade-haven', email: 'haven@demo.com', description: 'A little bit of everything — crocheted with heart.', location: 'Antipolo, Rizal', logo: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=200&h=200&fit=crop', banner: 'https://images.unsplash.com/photo-1506792006437-256b665541e2?w=1200&h=400&fit=crop' },
];

export const products = [
  // Seller 0: Yarn & Bloom Studio — crochet
  { si: 0, name: 'Crochet Sunflower Coaster Set', cat: ['crochet'], price: 180, desc: 'A set of 4 handmade sunflower coasters. Perfect table decor!', materials: '100% Cotton Yarn', tags: ['coaster','sunflower','home'], img: color('F4A261'), variants: [{name:'Yellow',stock:20,img:color('F4A261')},{name:'Orange',stock:15,img:color('E76F51')}] },
  { si: 0, name: 'Amigurumi Bear', cat: ['crochet','mini-stuffed-toy'], price: 350, desc: 'Cute mini teddy bear, 6 inches tall. Stuffed with premium polyester fill.', materials: 'Acrylic Yarn, Polyester Fill', tags: ['amigurumi','bear','gift'], img: color('D4A373'), variants: [{name:'Brown',stock:10,img:color('D4A373')},{name:'Cream',stock:8,img:color('FEFAE0')},{name:'Pink',stock:12,img:color('FFAFCC')}] },
  { si: 0, name: 'Crochet Bucket Hat', cat: ['crochet','accessories'], price: 420, desc: 'Trendy bucket hat crocheted with breathable cotton yarn.', materials: 'Cotton Blend Yarn', tags: ['hat','summer','fashion'], img: color('CDB4DB'), variants: [{name:'Lavender',stock:5,img:color('CDB4DB')},{name:'Sage',stock:7,img:color('A7C957')}] },
  { si: 0, name: 'Granny Square Tote Bag', cat: ['crochet','accessories'], price: 580, desc: 'Classic granny square pattern tote. Fully lined interior.', materials: 'Acrylic Yarn, Cotton Lining', tags: ['bag','tote','granny-square'], img: color('B5838D'), variants: [{name:'Multicolor',stock:6,img:color('B5838D')},{name:'Earth Tones',stock:4,img:color('6B705C')}] },
  { si: 0, name: 'Crochet Phone Pouch', cat: ['crochet','accessories'], price: 220, desc: 'Snug phone pouch with button closure. Fits most smartphones.', materials: 'Cotton Yarn', tags: ['phone','pouch','accessory'], img: color('577590'), variants: [{name:'Blue',stock:18,img:color('577590')},{name:'Mint',stock:14,img:color('83C5BE')}] },

  // Seller 1: Petals & Thread — crochet flower bouquets
  { si: 1, name: 'Rose Bouquet (6 stems)', cat: ['crochet-flower-bouquet'], price: 650, desc: 'A romantic bouquet of 6 hand-crocheted roses. Never wilts!', materials: 'Acrylic Yarn, Floral Wire', tags: ['rose','bouquet','gift','valentines'], img: color('E63946'), variants: [{name:'Classic Red',stock:10,img:color('E63946')},{name:'Blush Pink',stock:12,img:color('FFB4A2')},{name:'White',stock:8,img:color('F1FAEE')}] },
  { si: 1, name: 'Tulip Bouquet (5 stems)', cat: ['crochet-flower-bouquet'], price: 550, desc: 'Five cheerful tulips in a hand-tied arrangement.', materials: 'Cotton Yarn, Green Wire Stems', tags: ['tulip','bouquet','spring'], img: color('FFBE0B'), variants: [{name:'Yellow',stock:9,img:color('FFBE0B')},{name:'Purple',stock:7,img:color('7B2D8E')}] },
  { si: 1, name: 'Daisy Single Stem', cat: ['crochet-flower-bouquet'], price: 120, desc: 'A single crochet daisy — perfect for small gifts.', materials: 'Cotton Yarn', tags: ['daisy','single','affordable'], img: color('FFFFFF',400,500), variants: [{name:'White',stock:30,img:color('FFFFFF',400,500)},{name:'Pink',stock:25,img:color('FFC0CB',400,500)}] },
  { si: 1, name: 'Lavender Bundle', cat: ['crochet-flower-bouquet'], price: 380, desc: 'A dried-look lavender bundle. Includes 10 sprigs.', materials: 'Acrylic Yarn, Wire', tags: ['lavender','bundle','decor'], img: color('967BB6'), variants: [{name:'Purple',stock:14,img:color('967BB6')}] },
  { si: 1, name: 'Mixed Wildflower Bouquet', cat: ['crochet-flower-bouquet'], price: 780, desc: 'A vibrant mix of crocheted wildflowers. 8 unique stems.', materials: 'Acrylic Yarn, Floral Wire, Kraft Wrap', tags: ['wildflower','bouquet','premium'], img: color('2A9D8F'), variants: [{name:'Spring Mix',stock:5,img:color('2A9D8F')},{name:'Autumn Mix',stock:4,img:color('BC6C25')}] },

  // Seller 2: Fuzzy Wonders — fuzzy wire
  { si: 2, name: 'Fuzzy Wire Bear', cat: ['fuzzy-wire-art'], price: 280, desc: 'A cute bear figure made from fuzzy chenille wire.', materials: 'Chenille Wire, Felt', tags: ['bear','wire-art','cute'], img: color('C9ADA7'), variants: [{name:'Brown',stock:15,img:color('C9ADA7')},{name:'White',stock:10,img:color('F2E9E4')}] },
  { si: 2, name: 'Fuzzy Wire Cat', cat: ['fuzzy-wire-art'], price: 260, desc: 'A sitting cat sculpture. 4 inches tall.', materials: 'Chenille Wire', tags: ['cat','wire-art'], img: color('22223B'), variants: [{name:'Black',stock:12,img:color('22223B')},{name:'Orange Tabby',stock:9,img:color('E07A5F')}] },
  { si: 2, name: 'Fuzzy Sunflower Bouquet', cat: ['fuzzy-wire-bouquet'], price: 450, desc: '5 fuzzy wire sunflowers in a kraft paper wrap.', materials: 'Chenille Wire, Kraft Paper', tags: ['sunflower','bouquet','fuzzy'], img: color('FFD166'), variants: [{name:'Classic',stock:8,img:color('FFD166')}] },
  { si: 2, name: 'Fuzzy Rose Trio', cat: ['fuzzy-wire-bouquet'], price: 320, desc: 'Three fuzzy wire roses tied with a satin ribbon.', materials: 'Chenille Wire, Satin Ribbon', tags: ['rose','trio','gift'], img: color('EF476F'), variants: [{name:'Red',stock:14,img:color('EF476F')},{name:'Pink',stock:11,img:color('FFB5C2')}] },
  { si: 2, name: 'Fuzzy Wire Dinosaur', cat: ['fuzzy-wire-art'], price: 300, desc: 'An adorable T-Rex made entirely from chenille wire.', materials: 'Chenille Wire', tags: ['dinosaur','kids','fun'], img: color('06D6A0'), variants: [{name:'Green',stock:10,img:color('06D6A0')},{name:'Blue',stock:8,img:color('118AB2')}] },

  // Seller 3: Stitch & Soul — accessories / tops
  { si: 3, name: 'Crochet Crop Top', cat: ['tops'], price: 650, desc: 'A breezy crochet crop top for summer days.', materials: 'Cotton Yarn', tags: ['crop-top','summer','fashion'], img: color('FFE5D9'), variants: [{name:'S',stock:5,img:color('FFE5D9')},{name:'M',stock:8,img:color('FFE5D9')},{name:'L',stock:6,img:color('FFE5D9')}] },
  { si: 3, name: 'Crochet Halter Top', cat: ['tops'], price: 580, desc: 'Elegant halter neck design with adjustable ties.', materials: 'Bamboo Cotton Blend', tags: ['halter','top','elegant'], img: color('D8E2DC'), variants: [{name:'S',stock:4,img:color('D8E2DC')},{name:'M',stock:7,img:color('D8E2DC')},{name:'L',stock:5,img:color('D8E2DC')}] },
  { si: 3, name: 'Beaded Bracelet', cat: ['accessories'], price: 180, desc: 'Dainty beaded bracelet with yarn accents.', materials: 'Glass Beads, Cotton Thread', tags: ['bracelet','beaded','jewelry'], img: color('BDE0FE'), variants: [{name:'Blue',stock:20,img:color('BDE0FE')},{name:'Pink',stock:18,img:color('FFC8DD')},{name:'Gold',stock:12,img:color('DDA15E')}] },
  { si: 3, name: 'Crochet Earrings', cat: ['accessories'], price: 150, desc: 'Lightweight crocheted hoop earrings.', materials: 'Lace Thread, Metal Hoops', tags: ['earrings','crochet','lightweight'], img: color('A2D2FF'), variants: [{name:'White',stock:25,img:color('F1FAEE')},{name:'Blush',stock:20,img:color('FFAFCC')}] },
  { si: 3, name: 'Knit Headband', cat: ['accessories','hair-tie'], price: 200, desc: 'Cozy knit headband perfect for chilly mornings.', materials: 'Wool Blend Yarn', tags: ['headband','winter','cozy'], img: color('DDBEA9'), variants: [{name:'Beige',stock:15,img:color('DDBEA9')},{name:'Gray',stock:10,img:color('6C757D')}] },

  // Seller 4: Tiny Hooks PH — mini stuffed toys / keychains
  { si: 4, name: 'Mini Frog Keychain', cat: ['crochet-key-chains','mini-stuffed-toy'], price: 160, desc: 'A tiny crocheted frog that clips onto your keys.', materials: 'Cotton Yarn, Keychain Ring', tags: ['frog','keychain','mini'], img: color('4CAF50'), variants: [{name:'Green',stock:30,img:color('4CAF50')}] },
  { si: 4, name: 'Mushroom Keychain', cat: ['crochet-key-chains'], price: 140, desc: 'Cute mushroom amigurumi keychain. 2 inches tall.', materials: 'Acrylic Yarn', tags: ['mushroom','keychain','cottagecore'], img: color('FF6B6B'), variants: [{name:'Red',stock:25,img:color('FF6B6B')},{name:'Brown',stock:20,img:color('8B5E3C')}] },
  { si: 4, name: 'Mini Octopus', cat: ['mini-stuffed-toy'], price: 250, desc: 'Reversible mood octopus with happy/sad faces.', materials: 'Cotton Yarn, Safety Eyes', tags: ['octopus','reversible','mood'], img: color('7209B7'), variants: [{name:'Purple/Pink',stock:15,img:color('7209B7')},{name:'Blue/Yellow',stock:12,img:color('4361EE')}] },
  { si: 4, name: 'Tiny Duck Set (3pcs)', cat: ['mini-stuffed-toy'], price: 320, desc: 'Three adorable ducklings in graduating sizes.', materials: 'Acrylic Yarn, Polyester Fill', tags: ['duck','set','cute'], img: color('FFC300'), variants: [{name:'Yellow',stock:10,img:color('FFC300')}] },
  { si: 4, name: 'Cat Paw Keychain', cat: ['crochet-key-chains'], price: 130, desc: 'Squishy cat paw with toe beans. So soft!', materials: 'Cotton Yarn, Felt', tags: ['cat','paw','squishy'], img: color('FFB7C5'), variants: [{name:'Pink',stock:22,img:color('FFB7C5')},{name:'Gray',stock:18,img:color('ADB5BD')},{name:'Orange',stock:15,img:color('F4845F')}] },

  // Seller 5: Knot So Basic — tops
  { si: 5, name: 'Boho Crochet Vest', cat: ['tops'], price: 750, desc: 'Flowy boho vest with fringe details.', materials: 'Cotton Yarn', tags: ['vest','boho','fringe'], img: color('CCD5AE'), variants: [{name:'S',stock:4,img:color('CCD5AE')},{name:'M',stock:6,img:color('CCD5AE')},{name:'L',stock:3,img:color('CCD5AE')}] },
  { si: 5, name: 'Summer Tank Top', cat: ['tops'], price: 480, desc: 'Light and airy tank with open-stitch pattern.', materials: 'Bamboo Yarn', tags: ['tank','summer','breathable'], img: color('E9EDC9'), variants: [{name:'S',stock:7,img:color('E9EDC9')},{name:'M',stock:9,img:color('E9EDC9')}] },
  { si: 5, name: 'Patchwork Cardigan', cat: ['tops','crochet'], price: 1200, desc: 'Colorful granny square cardigan. One-of-a-kind.', materials: 'Acrylic Yarn Blend', tags: ['cardigan','patchwork','statement'], img: color('D4A276'), variants: [{name:'Multicolor - M',stock:2,img:color('D4A276')},{name:'Multicolor - L',stock:3,img:color('D4A276')}] },
  { si: 5, name: 'Off-Shoulder Blouse', cat: ['tops'], price: 620, desc: 'Romantic off-shoulder crochet blouse for date nights.', materials: 'Cotton Lace Yarn', tags: ['blouse','romantic','date-night'], img: color('FADADD'), variants: [{name:'S',stock:5,img:color('FADADD')},{name:'M',stock:4,img:color('FADADD')}] },

  // Seller 6: Loop & Lace — hair ties / accessories
  { si: 6, name: 'Scrunchie Set (5pcs)', cat: ['hair-tie','accessories'], price: 250, desc: 'Five handmade crochet scrunchies in pastel colors.', materials: 'Cotton Yarn, Elastic Band', tags: ['scrunchie','set','pastel'], img: color('BDB2FF'), variants: [{name:'Pastel Mix',stock:20,img:color('BDB2FF')},{name:'Earth Tones',stock:15,img:color('A68A64')}] },
  { si: 6, name: 'Bow Hair Clip', cat: ['hair-tie','accessories'], price: 120, desc: 'Cute crochet bow on an alligator clip.', materials: 'Cotton Yarn, Metal Clip', tags: ['bow','clip','cute'], img: color('FFC6FF'), variants: [{name:'Pink',stock:25,img:color('FFC6FF')},{name:'White',stock:20,img:color('FFFCF2')},{name:'Lavender',stock:18,img:color('E0BBE4')}] },
  { si: 6, name: 'Flower Hair Tie', cat: ['hair-tie'], price: 90, desc: 'Small crocheted flower on a soft elastic band.', materials: 'Cotton Thread, Elastic', tags: ['flower','hair-tie','everyday'], img: color('CAFFBF'), variants: [{name:'Daisy',stock:30,img:color('CAFFBF')},{name:'Rose',stock:28,img:color('FF99C8')}] },
  { si: 6, name: 'Pearl Headband', cat: ['hair-tie','accessories'], price: 280, desc: 'Crocheted headband adorned with faux pearl beads.', materials: 'Lace Thread, Faux Pearls', tags: ['headband','pearl','elegant'], img: color('FEFAE0'), variants: [{name:'Ivory',stock:10,img:color('FEFAE0')},{name:'Champagne',stock:8,img:color('D4A373')}] },

  // Seller 7: The Cozy Hook — crochet gifts
  { si: 7, name: 'Baby Blanket', cat: ['crochet'], price: 850, desc: 'Soft baby blanket in pastel chevron pattern. 30x30 inches.', materials: 'Baby-safe Acrylic Yarn', tags: ['baby','blanket','gift','newborn'], img: color('A8DADC'), variants: [{name:'Pastel Blue',stock:4,img:color('A8DADC')},{name:'Pastel Pink',stock:5,img:color('FFAFCC')},{name:'Mint',stock:3,img:color('B7E4C7')}] },
  { si: 7, name: 'Mug Cozy', cat: ['crochet'], price: 120, desc: 'Keeps your drink warm and your hands comfy.', materials: 'Acrylic Yarn, Button', tags: ['mug','cozy','office'], img: color('9B2335'), variants: [{name:'Burgundy',stock:20,img:color('9B2335')},{name:'Forest Green',stock:18,img:color('2D6A4F')}] },
  { si: 7, name: 'Crochet Storage Basket', cat: ['crochet'], price: 380, desc: 'Sturdy round basket for organizing small items.', materials: 'T-shirt Yarn', tags: ['basket','storage','home'], img: color('6C584C'), variants: [{name:'Natural',stock:8,img:color('6C584C')},{name:'Gray',stock:6,img:color('ADB5BD')}] },
  { si: 7, name: 'Plush Bunny', cat: ['crochet','mini-stuffed-toy'], price: 420, desc: 'Floppy-eared bunny plush. 10 inches of softness.', materials: 'Velvet Yarn, Polyester Fill', tags: ['bunny','plush','easter'], img: color('E8D5B7'), variants: [{name:'Cream',stock:6,img:color('E8D5B7')},{name:'Gray',stock:5,img:color('B7B7A4')}] },

  // Seller 8: Bloom Craft Co. — wire bouquets
  { si: 8, name: 'Wire Rose Arrangement', cat: ['fuzzy-wire-bouquet'], price: 520, desc: 'Elegant wire roses in a mini vase. Everlasting blooms.', materials: 'Craft Wire, Mini Ceramic Vase', tags: ['rose','wire','arrangement'], img: color('C1121F'), variants: [{name:'Red',stock:7,img:color('C1121F')},{name:'Gold',stock:5,img:color('DAA520')}] },
  { si: 8, name: 'Wire Cherry Blossom Branch', cat: ['fuzzy-wire-bouquet','fuzzy-wire-art'], price: 680, desc: 'Realistic cherry blossom branch. 12 inches long.', materials: 'Craft Wire, Tissue Paper', tags: ['cherry-blossom','branch','japanese'], img: color('FFB3C6'), variants: [{name:'Pink',stock:6,img:color('FFB3C6')}] },
  { si: 8, name: 'Wire Succulent Pot', cat: ['fuzzy-wire-art'], price: 350, desc: 'A wire succulent in a terracotta-style pot. Zero maintenance!', materials: 'Craft Wire, Mini Pot', tags: ['succulent','wire','plant'], img: color('588157'), variants: [{name:'Green',stock:10,img:color('588157')},{name:'Teal',stock:8,img:color('008080')}] },

  // Seller 9: Handmade Haven — mixed
  { si: 9, name: 'Crochet Wallet', cat: ['crochet','accessories'], price: 280, desc: 'Compact crocheted wallet with zipper closure.', materials: 'Cotton Yarn, Zipper', tags: ['wallet','compact','everyday'], img: color('264653'), variants: [{name:'Navy',stock:12,img:color('264653')},{name:'Tan',stock:10,img:color('E9C46A')}] },
  { si: 9, name: 'Boho Wall Hanging', cat: ['crochet'], price: 550, desc: 'Macramé-inspired crochet wall decor. 18 inches wide.', materials: 'Cotton Rope, Wooden Dowel', tags: ['wall-hanging','boho','decor'], img: color('DDA15E'), variants: [{name:'Natural',stock:5,img:color('DDA15E')}] },
  { si: 9, name: 'Crochet Bookmark Set', cat: ['crochet','accessories'], price: 150, desc: 'Set of 3 flower bookmarks. Perfect for book lovers.', materials: 'Lace Thread', tags: ['bookmark','flower','reader'], img: color('E9C46A'), variants: [{name:'Floral Mix',stock:25,img:color('E9C46A')}] },
  { si: 9, name: 'Mini Cactus Set', cat: ['crochet','mini-stuffed-toy'], price: 320, desc: 'Three crocheted cacti in tiny pots. Adorable desk decor.', materials: 'Cotton Yarn, Mini Pots', tags: ['cactus','desk','plant','set'], img: color('52B788'), variants: [{name:'Green Trio',stock:8,img:color('52B788')}] },
  { si: 9, name: 'Personalized Name Keychain', cat: ['crochet-key-chains'], price: 180, desc: 'Custom wire-bent name on a crochet base.', materials: 'Craft Wire, Cotton Yarn', tags: ['personalized','keychain','custom','gift'], img: color('F72585'), variants: [{name:'Custom',stock:50,img:color('F72585')}] },
];
