// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

const nodeEnv = (process.env.NODE_ENV || "").toLowerCase();
const envFile = nodeEnv === "development" ? ".env.development" : nodeEnv === "staging" ? ".env.staging" : ".env";
dotenv.config({ path: envFile });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
